### ISSUE TITLE
Multi query support

### ISSUE THREAD

**Issue by iantocristian** [hueniverse/penseur#103]
To take advantage of indexes in more complex queries, we would need a way to chain commands. 

The equivalent of:
```
r.db('db').table('table').getAll(['x', 'y'], {index:'type'}).filter(condition)
```

Suggested syntax:
```
db.table.query(db.chain(db.by(), condition)), ...)
```

**Comment by hueniverse** [comment]
I think this is the point where you need to use the driver directly. What we need is a generic way to use the existing connection and table to make any ReQL calls.

**Comment by iantocristian** [comment]
Agree.

**Comment by nathanpower** [comment]
Opened https://github.com/hueniverse/penseur/issues/106 for this
