### ISSUE TITLE
Support breaking large queries into smaller chunks

### ISSUE THREAD

**Issue by hueniverse** [hueniverse/penseur#115]

**Comment by Marsup** [comment]
Shouldn't you just use rethinkdb cursors for that ? The implementation feels wrong as you might be getting duplicate records under specific circumstances, also running the same query again and again is probably inefficient.

**Comment by hueniverse** [comment]
This is not the actual case. Rethink cursors do not have backpressure so when you ask for a lot of records, you will get them as soon as the server can send them. This means the client will be holding onto the full list and using a cursor is providing zero value vs. just converting to an array.

If you know of a way to use cursors + backpressure then this will not be needed. As for missing/duplicating, that can be true but it depends on how you sort the query and when you subscribe to the change feed. So there is nothing wrong about this but it is not as trivial as a single query.

**Comment by Marsup** [comment]
I don't know about the official driver but rethinkdbdash seem to support back pressure from what I can see in their code.
I think using this driver combined with the use of `includeInitial` (rdb 2.2+) in a changes request checks all your boxes in a single query.
