### ISSUE TITLE
Allow secondary indexes to be defined / created

### ISSUE THREAD

**Issue by iantocristian** [hueniverse/penseur#16]
Support objects in `tables` array argument for `table` / `establish` in addition to strings:

```
{
  name: 'user', 
  indexes: [...],
  truncate: false,
  ...
}
```

**Comment by hueniverse** [comment]
`db.table()` doesn't create tables, only `db.establish()`. It just creates an interface. This will be limited to the establish method and only to simple indexes. If you need access to multi or function handlers you will need to use the native module.
