### ISSUE TITLE
RethinkDB dependency

### ISSUE THREAD

**Issue by iantocristian** [hueniverse/penseur#53]
RethinkDB driver version numbers are aligned with the RethinkDB server version they work with, rather than anything else and the driver doesn't seem to provide backwards compatibility. 2.3.0 driver was just published which doesn't appear to work with RethinkDB server 2.2.x. The RethinkDB driver version should probably be locked with explicit updates reflected in the RethinkDB server requirements.

**Comment by hueniverse** [comment]
Temporarily solved with v4.1.2.
