### ISSUE TITLE
Nested keys with or

### ISSUE THREAD

**Issue by Marsup** [hueniverse/penseur#58]
I'm having a use case that seems impossible to do with penseur, would love to have your input.

Let's say I have data such as:
```js
[
  { a: { b: true, c: false }},
  { a: { c: true, d: true }}
]
```
And I would like to select it depending on the sub keys of a, so something like:
```js
{
  a: db.or([
    { c: true },
    { b: true }
  ])
}
```
It obviously doesn't work because the flattening of the filters only happens on objects and not on the function returned by db.or. Still I think that's a legitimate use case, not necessarily using this syntax.

**Comment by bengillies** [comment]
I'd just like to add:

I'd like to do something similar, but not on subkeys, so something like:

```javascript
table.query(db.or([
  { foo: 'bar' },
  { baz: 'qux' }
], (err, res) => {
  // ...
});
```
