### ISSUE TITLE
Add support for field comparators

### ISSUE THREAD

**Issue by Marsup** [hueniverse/penseur#74]
What do you think of adding support for [gt](https://rethinkdb.com/api/javascript/gt/), [ge](https://rethinkdb.com/api/javascript/ge/), [lt](https://rethinkdb.com/api/javascript/lt/), [le](https://rethinkdb.com/api/javascript/le/), ... ?

The current eq-only behavior is limiting us in some scenarios.

**Comment by hueniverse** [comment]
How complex does that need to be? support between? inside an or rule? contains?

**Comment by Marsup** [comment]
For now simple comparison of dates and numbers, between might be handy, not yet sure about or. What would be contains in this case ?

**Comment by hueniverse** [comment]
An array that contains number between two values, etc.

**Comment by Marsup** [comment]
Single values for now.

**Comment by iantocristian** [comment]
Yeah I take it the comparators would be functions so we would be able to combine them?

**Comment by iantocristian** [comment]
+1 on the request we really need this

**Comment by iantocristian** [comment]
This came up again, we need to be able to query on a subset of records based on date. +1

**Comment by iantocristian** [comment]
Is there a way to write a `between` query that wouldn't require the `db.and` operator? 

Looking to do a query similar to:

```
{
  a: 1, 
  b: db.and([{ c: db.is('>=', 10) }, { c: db.is('<=', 20) }]
}
```
