### ISSUE TITLE
db.and operator

### ISSUE THREAD

**Issue by iantocristian** [hueniverse/penseur#84]
To apply two conditions on the same key:

```
{ y: db.and([{ x: db.is('>', 100) }, { x: db.is('<', 200) }]) }
```

**Comment by hueniverse** [comment]
I rather solve this example within `db.is()` instead of adding another layer.

**Comment by iantocristian** [comment]
That works for us, but db.and would be handy to have as well. db.or appears to work correctly with the syntax above already.

**Comment by hueniverse** [comment]
I'll add is() and support and we'll leave this open until there is a use case not covered by it.
