### ISSUE TITLE
Reconnection backoff algorithm

### ISSUE THREAD

**Issue by Marsup** [hueniverse/penseur#89]
Penseur probably needs some kind of backoff algorithm to be softer on the CPU, because if rethinkdb goes down, the node process takes all the CPU. Something like https://en.wikipedia.org/wiki/Exponential_backoff ?

**Comment by hueniverse** [comment]
Does it need to be fancy? A simple timeout should be enough here since the concern is just CPU load.

**Comment by Marsup** [comment]
Usually the exponential backoff is one of the most efficient. It reconnects almost immediately on 1st disconnection (ideal for micro cuts) and ramps up to like several seconds (capped) where intermediary retries often help catch occasional service restarts faster and once you reach the capped limit it's a bigger problem. I'd suggest some modules to do that but I know you're not going to like it :D

**Comment by hueniverse** [comment]
I just don't think it's necessary. Try immediately the first time, then back off by a configured amount.
