### ISSUE TITLE
Purge default

### ISSUE THREAD

**Issue by shinzui** [hueniverse/penseur#90]
Hi,

I just started using penseur and I was surprised that the default behavior is to purge the declared tables' data. Shouldn't it default to false?

**Comment by hueniverse** [comment]
If you are referring to `establish()`, it is a "violent" method cleaning things up, usually used in tests and setup scripts. You should never use it in production runtime code.

**Comment by shinzui** [comment]
Thanks, it makes sense now. I learned the API thorough the tests, and I missed the `connect` method – I should have read the actual code.
