### ISSUE TITLE
Bulk Unsetting

### ISSUE THREAD

**Issue by simonmcmanus** [hueniverse/penseur#93]
We have a group table that identifies group membership on a users object like so: 

``` js
{
    users: {
        123: true,
        321: false
    }
}
```

We need to perform lots of updates/inserts/unsets against the users object across different groups. We currently call update multiple times which results in the subscribe event being fired for each update. 

We can batch the inserts/update together with an insert() merge:true but we also need to support db.unset(). 

What’s the best way to minimise the subscribe events that are fired for multiple updates/inserts/unsets across the group table? Is it possible to do the group update in one operation?

**Comment by hueniverse** [comment]
I don't think there is an easy solution to this but I'll think about it.
